### ISSUE TITLE
New feature discussion 

### ISSUE THREAD

**Issue by LuisLuii** [LuisLuii/FastAPIQuickCRUD#11]
After the foreign tree feature, I will focus on the Codegen feature, since #6 . Which make it easier for us to develop the API we want than now, you can modify the code to develop your own api based on this project

<img width="1679" alt="2022-03-07  9 36 03" src="https://user-images.githubusercontent.com/31765235/157044528-5009b649-4407-4a4c-8cd5-047965940325.png">

The CodeGen feature will not generate with `join_foreign_table` field 

13 mar 2022
The development is quite smooth and no blocking, I thing it can be released after 3 week

**Comment by aebrahim** [comment]
This looks awesome! I'll check it out and see how it works for my use case!

**Comment by LuisLuii** [comment]
> This looks awesome! I'll check it out and see how it works for my use case!

just released a new version that GET Request supports foreign tree
