### ISSUE TITLE
Which FastApi version is required ?

### ISSUE THREAD

**Issue by OlivierPonant** [LuisLuii/FastAPIQuickCRUD#4]
Hi, 

I would like to test your module which suits with my needs, but I'm facing out issue with tutorial/sample.py.
When I launch this, I get this error:
```
.\global_venv\lib\site-packages\fastapi_quickcrud\misc\schema_builder.py:263: UserWarning: The column of id has not default value and it is not nullable and in exclude_listit may throw error when you insert data 
  warnings.warn(
Traceback (most recent call last):
  File "./api/run3.py", line 23, in <module>
    crud_route_parent = generic_sql_crud_router_builder(
  File ".\global_venv\lib\site-packages\fastapi_quickcrud\crud_router.py", line 400, in crud_router_builder
    api = APIRouter(**router_kwargs)
TypeError: __init__() got an unexpected keyword argument 'sql_type'
```
It seems, the parameter sql_type is not expected by the FastApi class APIRouter. I checked quickly this class on FastAPI github, but I found no change for a while, missed I something ?

Best regards,

**Comment by LuisLuii** [comment]
I see. Let me check it

**Comment by LuisLuii** [comment]
Moreover, please using FastApi==0.68.2, It has been found that there is an adaptation problem after version 0.68.2. I will fix it in the next few days. If there is no special requirement, it is recommended to use 0.68.2 first.

**Comment by LuisLuii** [comment]
Also, It has been found that there is an adaptation problem after FastApi version 0.68.2. I will fix it in the next few days. If there is no special requirement, it is recommended to use fastapi-0.68.2 first.

**Comment by LuisLuii** [comment]
It has been found that there is an adaptation problem when using starlette > 0.14.2. I will fix it in the next few days. If there is no special requirement, it is recommended to use starlette <= 0.14.2

**Comment by LuisLuii** [comment]
It has been found that the version of starlette > 0.14.2 has an adaptation problem with asyncpg. If there is no special requirement, it is recommended to use starlette <= 0.14.2 first
